#!/bin/bash

set -euo pipefail

datasets="/path/to/datasets.tsv"

[[ -e "$datasets" ]] || (echo "File $datasets not found" && false)

nextflow run main.nf \
    --datasets "$datasets" \
    --outdir "results" \
    -resume
