#!/bin/bash

set -euo pipefail

samplefile="/path/to/sample.list"

[[ -e "$samplefile" ]] || (echo "File "$samplefile" not found" && false)

nextflow run cellgeni/nf-reprocessing-public-10x \
  --samplefile $samplefile \
  --ansi-log false \
  -resume
